<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xsl:stylesheet [<!ENTITY nbsp "&#160;">]>
<!--
     Copyright (C) 2011 Loic Dachary <loic@dachary.org>

     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.

     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with this program.  If not, see <http:www.gnu.org/licenses/>.
-->
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="html"
              encoding="UTF-8"
              doctype-public="-//W3C//DTD HTML 4.01//EN"
              doctype-system="http://www.w3.org/TR/html4/strict.dtd"
              indent="yes" />

  <xsl:param name="serial">0</xsl:param>

  <xsl:template match="/html/body">
    <body>
      <xsl:comment>
	DO NOT MODIFY THIS DOCUMENT. IT WAS GENERATED BY XSLT PROCESSING
	AND YOUR MODIFICATIONS WILL BE LOST. THE SOURCE OF THE DOCUMENT
	IS IN THE bug.xhtml FILE FOUND AT
        git clone git://anongit.freedesktop.org/libreoffice/website libreoffice
      </xsl:comment>
      <xsl:apply-templates select="node()"/>
    </body>
  </xsl:template>
  
  <xsl:template match="/html/head/script/@src">
    <xsl:attribute name="src"><xsl:value-of select='concat(.,"?",$serial)'></xsl:value-of></xsl:attribute>
  </xsl:template>

  <xsl:template match="/html/head/link/@href">
    <xsl:attribute name="href"><xsl:value-of select='concat(.,"?",$serial)'></xsl:value-of></xsl:attribute>
  </xsl:template>

  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

<!--
Local Variables: ***
mode: xml ***
End: ***
-->
</xsl:stylesheet>
